version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:235167363937:secret:docker_auth-ObCFIJ:docker_hub_username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:235167363937:secret:docker_auth-ObCFIJ:docker_hub_password

phases:
  pre_build:
    commands:
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      # コミット ID をイメージタグに設定
      - echo ImageTag=$IMAGE_TAG
      - echo Logging in to Docker Hub... $DOCKERHUB_USER / $DOCKERHUB_PASS
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - echo Logging in to Amazon ECR... hook test
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export KUBECTL_VERSION=1.25.0
      - echo Installing kubectl
      - wget -q https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
      - chmod 755 kubectl 
      - mv kubectl /usr/local/bin/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image... $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    # rollout kubernetes(eks) deployment
      - echo "rollout eks deployment"
      - aws eks update-kubeconfig --name my-cluster2 --region ap-northeast-1 --verbose
      - kubectl apply -f deployments/
