version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR... hook test
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export KUBECTL_VERSION=1.25.0
      - echo Installing kubectl
      - wget https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
      - chmod 755 kubectl 
      - mv kubectl /usr/local/bin/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    # rollout kubernetes(eks) deployment
      - echo "rollout eks deployment"
      - aws eks update-kubeconfig --name my-cluster2 --region ap-northeast-1 --verbose
      - kubectl rollout restart deployments/01-deployment.yaml -n eks-sample-app
